/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-09-07 05:40:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productmanagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Product Management</title>\r\n");
      out.write("\t<script src=\"script/productmanagement.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Product Management</h1>\r\n");
      out.write("<!-- =============================== -->\r\n");
      out.write("<!-- |   LIST OF CATEGORIES      | -->\r\n");
      out.write("<!-- =============================== -->\r\n");
      out.write("List of Categories:<br />\r\n");
      out.write("<div style=\"width:50%; float:left;\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t<th>Type</th>\r\n");
      out.write("\t\t\t<th>Is Perishable</th>\r\n");
      out.write("\t\t\t<th>Is Recyclable</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br /><br />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\t<!-- |   FOR ADDING NEW CATEGORY      | -->\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\tAdd Category:\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<form action=\"ProductManagement\" method=\"post\" >\r\n");
      out.write("\t\t\tName: <input type=\"text\" name=\"categoryName\" placeholder=\"category name\"> <br />\r\n");
      out.write("\t\t\tCategory Type:  <select name=\"categoryType\">\r\n");
      out.write("\t\t\t\t<option value=\"Beverages\" title=\"coffee/tea, juice, soda\">Beverages</option>\r\n");
      out.write("\t\t\t\t<option value=\"Bread/Bakery\" title=\"sandwich loaves, dinner rolls, tortillas, bagels\">Bread/Bakery</option>\r\n");
      out.write("\t\t\t\t<option value=\"Canned/Jarred Goods\" title=\"vegetables, spaghetti sauce, ketchup\">Canned/Jarred Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Dry/Baking Goods\">Dry/Baking Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Frozen Foods\">Frozen Foods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Meat\">Meat</option>\r\n");
      out.write("\t\t\t\t<option value=\"Produce\">Produce</option>\r\n");
      out.write("\t\t\t\t<option value=\"Cleaners\">Cleaners</option>\r\n");
      out.write("\t\t\t\t<option value=\"Paper Goods\">Paper Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Personal Care\">Personal Care</option>\r\n");
      out.write("\t\t\t\t<option value=\"Other\" selected>Other</option>\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\tPerishable: <input type=\"radio\" name=\"perishable\" value=\"true\" onclick=\"disableRecyclableButtons()\"> \r\n");
      out.write("\t\t\t\tNon Perishable: <input type=\"radio\" name=\"perishable\" value=\"false\" onclick=\"enableRecyclableButtons()\" checked><br />\r\n");
      out.write("\t\t\t\tRecyclable: <input id=\"radRecyclable\" type=\"radio\" name=\"recyclable\" value=\"true\"> \r\n");
      out.write("\t\t\t\tNot Recyclable: <input id=\"radNotRecyclable\" type=\"radio\" name=\"recyclable\" value=\"false\" checked>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"addCategory\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\t<!-- |   LIST OF PRODUCTS      | -->\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\tList of Products:<br />\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Category</th>\r\n");
      out.write("\t\t\t<th>SKU</th>\r\n");
      out.write("\t\t\t<th>Brand</th>\r\n");
      out.write("\t\t\t<th>Variant</th>\r\n");
      out.write("\t\t\t<th>Size</th>\r\n");
      out.write("\t\t\t<th>Description</th>\r\n");
      out.write("\t\t\t<th>Special Handling</th>\r\n");
      out.write("\t\t\t<th>Selling Price</th>\r\n");
      out.write("\t\t\t<th>Stock Amount</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br /><br />\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\t<!-- |   FOR ADDING NEW PRODUCT      | -->\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\tAdd Product:\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<form action=\"ProductManagement\" method=\"post\">\r\n");
      out.write("\t\t\tCategory:  <select id=\"addProdCategory\" name=\"categoryId\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\tBrand: <input id=\"addProdBrand\" type=\"text\" name=\"brand\" placeholder=\"brand\" /> <br />\r\n");
      out.write("\t\t\tVariant: <input id=\"addProdVariant\" type=\"text\" name=\"variant\" value=\"none\" placeholder=\"none\" /> <br />\r\n");
      out.write("\t\t\tSize: <input id=\"addProdSize\" type=\"text\" name=\"size\" placeholder=\"size\" />\r\n");
      out.write("\t\t\t<input id=\"addProdUnit\" type=\"text\" name=\"measurementUnit\" placeholder=\"unit\" /> <br />\r\n");
      out.write("\t\t\tDescription: <textarea name=\"description\" placeholder=\"description\" rows=\"3\" cols=\"40\"></textarea> <br />\r\n");
      out.write("\t\t\tSpecial Handling: <select name=\"specialHandling\">\r\n");
      out.write("\t\t\t\t<option value=\"\" selected></option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">keep frozen</option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">keep refrigerated</option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">fragile</option>\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\tSelling Price: Php<input type=\"number\" name=\"sellPrice\" placeholder=\"sell price\" step=\"0.01\"> <br /><br />\r\n");
      out.write("\t\t\tSKU: <input id=\"addProdSKU\" type=\"text\" name=\"SKU\" placeholder=\"Stock Keeping Unit\">\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"generateSKU()\">Generate</button> <br />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"addProduct\" /> \r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\tInput items\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- ==============================================================================================================-->\r\n");
      out.write("<!-- ======================================== EDITING AND DELETING ================================================-->\r\n");
      out.write("<!-- ==============================================================================================================-->\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:50%; float:right;\">\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\t<!-- |   FOR EDITING CATEGORY      | -->\r\n");
      out.write("\t<!-- =============================== -->\r\n");
      out.write("\t<div id=\"editCategoryForm\" style=\"width:50%; float:right; visibility: hidden\">\r\n");
      out.write("\t\tCategory Details:\r\n");
      out.write("\t\t<form action=\"ProductManagement\" method=\"post\">\r\n");
      out.write("\t\t\tName: <input id=\"txtCategoryName\" type=\"text\" name=\"categoryName\" placeholder=\"category name\" /> <br />\r\n");
      out.write("\t\t\tCategory Type:  <select id=\"selCategoryType\" name=\"categoryType\">\r\n");
      out.write("\t\t\t\t<option value=\"Beverages\" title=\"coffee/tea, juice, soda\">Beverages</option>\r\n");
      out.write("\t\t\t\t<option value=\"Bread/Bakery\" title=\"sandwich loaves, dinner rolls, tortillas, bagels\">Bread/Bakery</option>\r\n");
      out.write("\t\t\t\t<option value=\"Canned/Jarred Goods\" title=\"vegetables, spaghetti sauce, ketchup\">Canned/Jarred Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Dry/Baking Goods\">Dry/Baking Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Frozen Foods\">Frozen Foods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Meat\">Meat</option>\r\n");
      out.write("\t\t\t\t<option value=\"Produce\">Produce</option>\r\n");
      out.write("\t\t\t\t<option value=\"Cleaners\">Cleaners</option>\r\n");
      out.write("\t\t\t\t<option value=\"Paper Goods\">Paper Goods</option>\r\n");
      out.write("\t\t\t\t<option value=\"Personal Care\">Personal Care</option>\r\n");
      out.write("\t\t\t\t<option value=\"Other\">Other</option>\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\tPerishable: <input id=\"radEditPerishable\" type=\"radio\" name=\"perishable\" value=\"true\" onclick=\"disableEditRecyclableButtons()\" /> \r\n");
      out.write("\t\t\t\tNon Perishable: <input id=\"radEditNonPerishable\" type=\"radio\" name=\"perishable\" value=\"false\" onclick=\"enableEditRecyclableButtons()\" checked /><br />\r\n");
      out.write("\t\t\t\tRecyclable: <input id=\"radEditRecyclable\" type=\"radio\" name=\"recyclable\" value=\"true\" /> \r\n");
      out.write("\t\t\t\tNot Recyclable: <input id=\"radEditNotRecyclable\" type=\"radio\" name=\"recyclable\" value=\"false\" checked />\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<input id=\"txtCategoryId\" type=\"hidden\" name=\"categoryId\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"editCategory\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Update\" /><br />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<form action=\"ProductManagement\" method=\"post\">\r\n");
      out.write("\t\t\t<input id=\"txtCategoryId2\" type=\"hidden\" name=\"categoryId\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"deleteCategory\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Remove Category\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"editProductForm\" >\r\n");
      out.write("\t\t<form action=\"ProductManagement\" method=\"post\" >\r\n");
      out.write("\t\t\tCategory:  <select id=\"editProdCategory\" name=\"categoryId\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\tBrand: <input id=\"editProdBrand\" type=\"text\" name=\"brand\" placeholder=\"brand\" /> <br />\r\n");
      out.write("\t\t\tVariant: <input id=\"editProdVariant\" type=\"text\" name=\"variant\" value=\"none\" placeholder=\"none\" /> <br />\r\n");
      out.write("\t\t\tSize: <input id=\"editProdSize\" type=\"text\" name=\"size\" placeholder=\"size\" />\r\n");
      out.write("\t\t\t<input id=\"editProdUnit\" type=\"text\" name=\"measurementUnit\" placeholder=\"unit\" /> <br />\r\n");
      out.write("\t\t\tDescription: <textarea id = \"editProdDescription\" name=\"description\" placeholder=\"description\" rows=\"3\" cols=\"40\"></textarea> <br />\r\n");
      out.write("\t\t\tSpecial Handling: <select id=\"editProdSpecialHandling\" name=\"specialHandling\">\r\n");
      out.write("\t\t\t\t<option value=\"\" selected></option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">keep frozen</option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">keep refrigerated</option>\r\n");
      out.write("\t\t\t\t<option value=\"keep frozen\">fragile</option>\r\n");
      out.write("\t\t\t</select> <br />\r\n");
      out.write("\t\t\tSelling Price: Php<input id=\"editProdSellPrice\" type=\"number\" name=\"sellPrice\" placeholder=\"sell price\" step=\"0.01\"> <br /><br />\r\n");
      out.write("\t\t\tSKU: <input id=\"editProdSKU\" type=\"text\" name=\"SKU\" placeholder=\"Stock Keeping Unit\" />\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"generateSKU()\">Generate</button> <br />\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"action\" value=\"addProduct\" />\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /productmanagement.jsp(25,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/productmanagement.jsp(25,2) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /productmanagement.jsp(25,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<td onclick=\"showCategoryDetails('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.isPerishable}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.isRecyclable}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /productmanagement.jsp(84,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/productmanagement.jsp(84,2) '${productList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /productmanagement.jsp(84,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("product");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t<tr>\r\n");
            out.write("\t\t\t\t<td onclick=\"showProductDetails('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.category.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.SKU}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.brand}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.variant}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.size}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.measurementUnit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.specialHandling}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.sellPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.stockAmount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /productmanagement.jsp(106,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/productmanagement.jsp(106,4) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /productmanagement.jsp(106,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("category");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /productmanagement.jsp(178,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/productmanagement.jsp(178,4) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /productmanagement.jsp(178,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("category");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" title=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.categoryName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</option>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
