/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-08-31 09:20:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productmanagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Product Management</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"script/productmanagement.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Product Management</h1>\r\n");
      out.write("<!-- =============================== -->\r\n");
      out.write("<!-- |   FOR ADDING NEW PRODUCTS      | -->\r\n");
      out.write("<!-- =============================== -->\r\n");
      out.write("Add Category\r\n");
      out.write("<fieldset>\r\n");
      out.write("\t<form action=\"ProductManagement\" method=\"post\" >\r\n");
      out.write("\t\tName: <input type=\"text\" name=\"name\" placeholder=\"category name\"> <br>\r\n");
      out.write("\t\tProduct Type:  <select name=\"productType\">\r\n");
      out.write("\t\t\t<option value=\"Beverages\" title=\"coffee/tea, juice, soda\">Beverages</option>\r\n");
      out.write("\t\t\t<option value=\"Bread/Bakery\" title=\"sandwich loaves, dinner rolls, tortillas, bagels\">Bread/Bakery</option>\r\n");
      out.write("\t\t\t<option value=\"Canned/Jarred Goods\" title=\"vegetables, spaghetti sauce, ketchup\">Canned/Jarred Goods</option>\r\n");
      out.write("\t\t\t<option value=\"Dry/Baking Goods\">Dry/Baking Goods</option>\r\n");
      out.write("\t\t\t<option value=\"Frozen Foods\">Frozen Foods</option>\r\n");
      out.write("\t\t\t<option value=\"Meat\">Meat</option>\r\n");
      out.write("\t\t\t<option value=\"Produce\">Produce</option>\r\n");
      out.write("\t\t\t<option value=\"Cleaners\">Cleaners</option>\r\n");
      out.write("\t\t\t<option value=\"Paper Goods\">Paper Goods</option>\r\n");
      out.write("\t\t\t<option value=\"Personal Care\">Personal Care</option>\r\n");
      out.write("\t\t\t<option value=\"Other\" selected>Other</option>\r\n");
      out.write("\t\t</select> <br>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\tPerishable: <input type=\"radio\" name=\"perishable\" value=\"true\" onclick=\"disableRecyclableButtons()\"> \r\n");
      out.write("\t\t\tNon Perishable: <input type=\"radio\" name=\"perishable\" value=\"false\" onclick=\"enableRecyclableButtons()\" checked><br>\r\n");
      out.write("\t\t\tRecyclable: <input id=\"radRecyclable\" type=\"radio\" name=\"recyclable\" value=\"true\"> \r\n");
      out.write("\t\t\tNot Recyclable: <input id=\"radNotRecyclable\" type=\"radio\" name=\"recyclable\" value=\"false\" checked>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"action\" value=\"addCategory\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</fieldset>\r\n");
      out.write("<br>\r\n");
      out.write("Add Product\r\n");
      out.write("<br>\r\n");
      out.write("Input items\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
